from typing import List, Dict, Any, Tuple
from app.services.extraction.base import ExtractorStrategy
from app.services.extraction.normalizer import ObligationNormalizer


class DemoExtractor(ExtractorStrategy):
    """
    High-fidelity deterministic extractor for the bundled demo agreement.
    Guarantees 100% reliable presentation execution with explainable evidence citations.
    """

    def extract(
        self, contract_text: str, pages_data: List[Dict[str, Any]]
    ) -> Tuple[List[Dict[str, Any]], List[Dict[str, Any]], List[Dict[str, Any]]]:
        parties = [
            {"name": "Ms. Priya Verma", "role": "Tenant"},
            {"name": "Mr. Rajesh Sharma", "role": "Landlord"},
        ]

        raw_clauses = [
            {
                "clause_number": "1",
                "title": "Parties and Demised Premises",
                "page_number": 1,
                "text": "This Residential Tenancy Agreement is made and entered into on this 1st day of January 2026, by and between Mr. Rajesh Sharma (hereinafter referred to as the 'Landlord') of the FIRST PART, and Ms. Priya Verma (hereinafter referred to as the 'Tenant') of the SECOND PART. The Landlord hereby lets and the Tenant agrees to take on rent the residential premises located at Flat 402, Greenview Heights, Sector 14, Gurugram, Haryana.",
                "preview": "Identifies Landlord Mr. Rajesh Sharma and Tenant Ms. Priya Verma letting Flat 402, Greenview Heights.",
            },
            {
                "clause_number": "2",
                "title": "Term and Commencement",
                "page_number": 1,
                "text": "The initial term of this tenancy shall be for a duration of 11 (eleven) months commencing on January 1, 2026, and expiring on November 30, 2026, unless renewed earlier by mutual written agreement. Any renewal shall require a fresh written agreement executed at least 30 days prior to the expiration of the ongoing term with mutually agreed escalation in rent.",
                "preview": "11-month lease term from Jan 1, 2026 to Nov 30, 2026, requiring 30 days renewal notice.",
            },
            {
                "clause_number": "3",
                "title": "Monthly Rent and Late Fees",
                "page_number": 1,
                "text": "The Tenant shall pay to the Landlord a monthly rent of ₹20,000 (Rupees Twenty Thousand only) on or before the 5th day of each calendar month in advance via direct electronic bank transfer. In the event of default or delayed payment, the Tenant agrees to pay a late payment fee of ₹500 per day of delay calculated from the 6th day of the month until the entire outstanding sum is remitted in full. Continued default exceeding 15 days shall constitute grounds for immediate termination.",
                "preview": "Tenant must pay ₹20,000 monthly rent on or before the 5th. Late fee of ₹500/day applies upon delay.",
            },
            {
                "clause_number": "4",
                "title": "Security Deposit and Refund",
                "page_number": 1,
                "text": "The Tenant shall deposit and maintain with the Landlord an interest-free refundable security deposit of ₹60,000 (Rupees Sixty Thousand only) upon execution of this agreement. The Landlord shall refund the security deposit within 30 days following the peaceful surrender of the premises, subject to permitted deductions for unpaid rent, unpaid utility dues, or documented structural damages beyond normal wear and tear.",
                "preview": "Security deposit of ₹60,000 to be refunded within 30 days post-tenancy subject to deductions.",
            },
            {
                "clause_number": "5",
                "title": "Utility Bills and Municipal Outgoings",
                "page_number": 2,
                "text": "The Tenant shall promptly pay all charges for electricity, water, cooking gas, and high-speed internet consumed within 7 days of receiving the respective bill. The Tenant shall furnish copies of paid utility receipts to the Landlord upon request no later than the 10th of each calendar month. The Landlord shall remain solely liable for statutory property tax and building capital society sinking funds.",
                "preview": "Tenant pays utility charges within 7 days of invoice and furnishes receipts on request.",
            },
            {
                "clause_number": "6",
                "title": "Maintenance and Structural Repairs",
                "page_number": 2,
                "text": "The Landlord shall complete necessary major structural and plumbing repairs within 7 days of written notification from the Tenant, provided such damage is not caused by the willful negligence or misuse of the Tenant. The Tenant is responsible for day-to-day cleanliness, waste disposal, and minor repairs of fuses, light bulbs, tap washers, and fittings at their own expense throughout the subsistence of the tenancy.",
                "preview": "Landlord completes structural repairs within 7 days. Tenant handles day-to-day minor repairs.",
            },
            {
                "clause_number": "7",
                "title": "Permitted Use and Prohibitions",
                "page_number": 2,
                "text": "The Tenant agrees to use the premises strictly for private residential accommodation and shall not operate any commercial enterprise, business, or illegal activity therein. The Tenant shall not sublet, assign, or part with possession of the premises or any part thereof to any third party without obtaining prior written approval from the Landlord.",
                "preview": "Strictly residential use. Commercial operations and unauthorized subletting are prohibited.",
            },
            {
                "clause_number": "8",
                "title": "Landlord Right of Inspection and Entry",
                "page_number": 3,
                "text": "The Landlord or their authorized agent shall give at least 24 hours prior written notice before entering the premises for physical inspection or repair assessment. The Tenant shall permit inspection access during reasonable daylight hours between 10:00 AM and 6:00 PM following due notice, except in case of urgent emergency involving water leakage or fire.",
                "preview": "Landlord must provide 24 hours written notice before entering for daylight inspection.",
            },
            {
                "clause_number": "9",
                "title": "Alterations and Improvements",
                "page_number": 3,
                "text": "The Tenant shall not carry out any structural alterations, permanent wall drillings, or repaintings without prior written consent from the Landlord. In the event of unapproved modifications, the Tenant shall restore the premises to its pristine original condition at the Tenant's sole expense prior to final vacation.",
                "preview": "Structural alterations require prior written consent. Tenant must restore unauthorized changes.",
            },
            {
                "clause_number": "10",
                "title": "Termination and Notice Period",
                "page_number": 3,
                "text": "Either party may terminate this agreement prior to the expiry of the lease term by providing at least 30 days prior written notice to the other party. If the Tenant vacates without serving the mandatory 30 days notice, the Landlord shall be entitled to forfeit one month's rent in lieu of notice. The Landlord may terminate with 7 days notice in the event of persistent breach of covenant.",
                "preview": "30 days prior written notice required by either party for early termination.",
            },
            {
                "clause_number": "11",
                "title": "Surrender of Premises and Key Handover",
                "page_number": 3,
                "text": "The Tenant shall surrender vacant possession and return all original keys and access fobs to the Landlord by 12:00 PM on the final day of the tenancy. If the Tenant fails to vacate upon expiry or termination, the Tenant shall pay an unauthorized holding over charge of ₹2,000 per calendar day until actual possession is delivered.",
                "preview": "Tenant must return keys by 12:00 PM on final day. Unauthorized stay incurs ₹2,000/day charge.",
            },
            {
                "clause_number": "12",
                "title": "Governing Law and Dispute Resolution",
                "page_number": 4,
                "text": "This Agreement shall be governed and construed in accordance with the laws of India and the courts at Gurugram shall have exclusive jurisdiction. Both parties agree to attempt amicable conciliation within 15 days of written notice of any controversy prior to initiating formal arbitration proceedings under the Arbitration and Conciliation Act, 1996.",
                "preview": "Disputes subject to 15 days amicable conciliation before formal arbitration under Indian law.",
            },
        ]

        raw_obligations = [
            {
                "clause_number": "3",
                "actor": "Tenant",
                "action": "Pay monthly rent",
                "object": "Monthly rent",
                "amount": "₹20,000",
                "frequency": "Monthly",
                "trigger": "Beginning of each rental month",
                "condition": None,
                "deadline_text": "on or before the 5th day of each calendar month",
                "normalized_deadline": "Day 5 of every month",
                "consequence": "Late payment fee of ₹500 per day of delay",
                "status": "Pending",
                "confidence": 0.96,
                "evidence_text": "The Tenant shall pay to the Landlord a monthly rent of ₹20,000 on or before the 5th day of each calendar month in advance via direct electronic bank transfer.",
                "source_page": 1,
            },
            {
                "clause_number": "3",
                "actor": "Tenant",
                "action": "Pay late payment fee",
                "object": "Late penalty",
                "amount": "₹500/day",
                "frequency": "Daily upon delay",
                "trigger": "Delayed payment beyond the 5th day",
                "condition": "If rent remains unpaid beyond the 5th day of the month",
                "deadline_text": "calculated from the 6th day until remitted in full",
                "normalized_deadline": "Immediate upon breach",
                "consequence": "Termination after 15 days default",
                "status": "Pending",
                "confidence": 0.92,
                "evidence_text": "In the event of default or delayed payment, the Tenant agrees to pay a late payment fee of ₹500 per day of delay calculated from the 6th day of the month until the entire outstanding sum is remitted in full.",
                "source_page": 1,
            },
            {
                "clause_number": "4",
                "actor": "Tenant",
                "action": "Deposit security deposit",
                "object": "Interest-free refundable deposit",
                "amount": "₹60,000",
                "frequency": "One-time",
                "trigger": "Execution of tenancy agreement",
                "condition": None,
                "deadline_text": "upon execution of this agreement",
                "normalized_deadline": "Contract signing date",
                "consequence": "Withholding of possession",
                "status": "Completed",
                "confidence": 0.95,
                "evidence_text": "The Tenant shall deposit and maintain with the Landlord an interest-free refundable security deposit of ₹60,000 upon execution of this agreement.",
                "source_page": 1,
            },
            {
                "clause_number": "4",
                "actor": "Landlord",
                "action": "Refund security deposit",
                "object": "Security deposit refund",
                "amount": "₹60,000 (less deductions)",
                "frequency": "One-time",
                "trigger": "End of tenancy and peaceful surrender of premises",
                "condition": "Subject to permitted deductions for unpaid rent, utilities, or documented damages",
                "deadline_text": "within 30 days following the peaceful surrender of the premises",
                "normalized_deadline": "Tenancy end date + 30 days",
                "consequence": "Legal claim for wrongful withholding",
                "status": "Pending",
                "confidence": 0.93,
                "evidence_text": "The Landlord shall refund the security deposit within 30 days following the peaceful surrender of the premises, subject to permitted deductions.",
                "source_page": 1,
            },
            {
                "clause_number": "5",
                "actor": "Tenant",
                "action": "Pay utility charges",
                "object": "Electricity, water, gas, and internet bills",
                "amount": "Actual billing amount",
                "frequency": "Monthly",
                "trigger": "Receipt of respective utility invoice",
                "condition": None,
                "deadline_text": "within 7 days of receiving the respective bill",
                "normalized_deadline": "Bill receipt + 7 days",
                "consequence": "Utility disconnection and recovery by Landlord",
                "status": "Pending",
                "confidence": 0.94,
                "evidence_text": "The Tenant shall promptly pay all charges for electricity, water, cooking gas, and high-speed internet consumed within 7 days of receiving the respective bill.",
                "source_page": 2,
            },
            {
                "clause_number": "5",
                "actor": "Tenant",
                "action": "Furnish utility receipts",
                "object": "Copies of paid utility receipts",
                "amount": None,
                "frequency": "Monthly",
                "trigger": "Landlord request",
                "condition": "Upon request by the Landlord",
                "deadline_text": "no later than the 10th of each calendar month",
                "normalized_deadline": "Day 10 of each month",
                "consequence": "Default presumption",
                "status": "Pending",
                "confidence": 0.88,
                "evidence_text": "The Tenant shall furnish copies of paid utility receipts to the Landlord upon request no later than the 10th of each calendar month.",
                "source_page": 2,
            },
            {
                "clause_number": "6",
                "actor": "Landlord",
                "action": "Complete major structural repairs",
                "object": "Major structural and plumbing repairs",
                "amount": None,
                "frequency": "As needed",
                "trigger": "Tenant reports qualifying maintenance issue in writing",
                "condition": "Provided damage is not caused by willful negligence of Tenant",
                "deadline_text": "within 7 days of written notification from the Tenant",
                "normalized_deadline": "Notice date + 7 days",
                "consequence": "Tenant right to repair and offset from subsequent rent",
                "status": "Pending",
                "confidence": 0.92,
                "evidence_text": "The Landlord shall complete necessary major structural and plumbing repairs within 7 days of written notification from the Tenant, provided such damage is not caused by the willful negligence or misuse of the Tenant.",
                "source_page": 2,
            },
            {
                "clause_number": "6",
                "actor": "Tenant",
                "action": "Maintain minor fixtures and cleanliness",
                "object": "Fuses, light bulbs, tap washers, and fittings",
                "amount": None,
                "frequency": "Ongoing",
                "trigger": "Occupancy",
                "condition": None,
                "deadline_text": "throughout the subsistence of the tenancy",
                "normalized_deadline": "Continuous lease term",
                "consequence": "Deduction from security deposit",
                "status": "Pending",
                "confidence": 0.89,
                "evidence_text": "The Tenant is responsible for day-to-day cleanliness, waste disposal, and minor repairs of fuses, light bulbs, tap washers, and fittings at their own expense throughout the subsistence of the tenancy.",
                "source_page": 2,
            },
            {
                "clause_number": "8",
                "actor": "Landlord",
                "action": "Give advance inspection notice",
                "object": "Prior written inspection notice",
                "amount": None,
                "frequency": "Per inspection",
                "trigger": "Intent to inspect premises",
                "condition": "Except in urgent emergency involving water leakage or fire",
                "deadline_text": "at least 24 hours prior written notice",
                "normalized_deadline": "Inspection time - 24 hours",
                "consequence": "Tenant refusal permitted",
                "status": "Pending",
                "confidence": 0.91,
                "evidence_text": "The Landlord or their authorized agent shall give at least 24 hours prior written notice before entering the premises for physical inspection or repair assessment.",
                "source_page": 3,
            },
            {
                "clause_number": "10",
                "actor": "Tenant",
                "action": "Provide termination notice",
                "object": "Prior written termination notice",
                "amount": None,
                "frequency": "One-time",
                "trigger": "Intention to terminate agreement prior to natural expiry",
                "condition": None,
                "deadline_text": "at least 30 days prior written notice",
                "normalized_deadline": "Termination date - 30 days",
                "consequence": "Forfeiture of one month's rent in lieu of notice",
                "status": "Pending",
                "confidence": 0.94,
                "evidence_text": "Either party may terminate this agreement prior to the expiry of the lease term by providing at least 30 days prior written notice to the other party.",
                "source_page": 3,
            },
            {
                "clause_number": "10",
                "actor": "Landlord",
                "action": "Provide termination notice",
                "object": "Prior written termination notice",
                "amount": None,
                "frequency": "One-time",
                "trigger": "Intention to terminate agreement or persistent covenant breach",
                "condition": "7 days in event of persistent covenant breach",
                "deadline_text": "at least 30 days written notice",
                "normalized_deadline": "Termination date - 30 days",
                "consequence": "Invalid termination",
                "status": "Pending",
                "confidence": 0.91,
                "evidence_text": "The Landlord may terminate with 7 days notice in the event of persistent breach of covenant or at least 30 days written notice.",
                "source_page": 3,
            },
            {
                "clause_number": "11",
                "actor": "Tenant",
                "action": "Surrender keys and vacant possession",
                "object": "Keys, access fobs, and vacant possession",
                "amount": None,
                "frequency": "One-time",
                "trigger": "Final day of tenancy",
                "condition": None,
                "deadline_text": "by 12:00 PM on the final day of the tenancy",
                "normalized_deadline": "Final day 12:00 PM",
                "consequence": "Holding over charge of ₹2,000 per calendar day",
                "status": "Pending",
                "confidence": 0.95,
                "evidence_text": "The Tenant shall surrender vacant possession and return all original keys and access fobs to the Landlord by 12:00 PM on the final day of the tenancy.",
                "source_page": 3,
            },
            {
                "clause_number": "12",
                "actor": "Either party",
                "action": "Attempt amicable conciliation",
                "object": "Conciliation and dispute negotiation",
                "amount": None,
                "frequency": "Upon dispute",
                "trigger": "Any controversy or claim arising under this agreement",
                "condition": "Prior to initiating formal arbitration",
                "deadline_text": "within 15 days of written notice of any controversy",
                "normalized_deadline": "Dispute notice + 15 days",
                "consequence": "Referral to formal arbitration",
                "status": "Pending",
                "confidence": 0.88,
                "evidence_text": "Both parties agree to attempt amicable conciliation within 15 days of written notice of any controversy prior to initiating formal arbitration proceedings.",
                "source_page": 4,
            },
        ]

        # Attach attention flags to clauses
        clauses_with_flags = []
        for c in raw_clauses:
            clause_obls = [o for o in raw_obligations if o["clause_number"] == c["clause_number"]]
            flags = ObligationNormalizer.extract_attention_flags(c["title"], c["text"], clause_obls)
            c_copy = dict(c)
            c_copy["attention_flags"] = flags
            c_copy["obligation_count"] = len(clause_obls)
            clauses_with_flags.append(c_copy)

        return parties, clauses_with_flags, raw_obligations
